# Generated by Django 4.2.3 on 2023-09-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanchetasIgm', '0003_remove_igm_mpoly_altmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='igm_mpoly',
            name='comprado',
            field=models.BooleanField(default=False),
        ),
    ]
