# Generated by Django 4.2.3 on 2023-09-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanchetasIgm', '0004_igm_mpoly_comprado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='igm_mpoly',
            name='base',
        ),
        migrations.RemoveField(
            model_name='igm_mpoly',
            name='clamped',
        ),
        migrations.RemoveField(
            model_name='igm_mpoly',
            name='extruded',
        ),
        migrations.RemoveField(
            model_name='igm_mpoly',
            name='popupinfo',
        ),
        migrations.RemoveField(
            model_name='igm_mpoly',
            name='snippet',
        ),
        migrations.RemoveField(
            model_name='igm_mpoly',
            name='symbolid',
        ),
    ]
