# Generated by Django 4.2.3 on 2023-09-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanchetasIgm', '0006_alter_igm_mpoly_options_remove_igm_mpoly_comprado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='igm_mpoly',
            name='area',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='igm_mpoly',
            name='bought',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='igm_mpoly',
            name='directory',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='igm_mpoly',
            name='owner',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
