# Generated by Django 4.2.3 on 2023-09-02 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanchetasIgm', '0007_igm_mpoly_area_igm_mpoly_bought_igm_mpoly_directory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='igm_mpoly',
            options={'ordering': ['bought', 'name'], 'verbose_name': 'Planchetas IGM', 'verbose_name_plural': 'Planchetas IGM'},
        ),
    ]
